namespace Runtime.Engine.Jobs.Chunk
{
    public struct GeneratorConfig
    {
        public int BrickGrey;
        public int BrickRed;
        public int Cactus;
        public int CottonBlue;
        public int CottonGreen;
        public int CottonRed;
        public int CottonTan;
        public int Dirt;
        public int DirtGravel;
        public int DirtSandy;
        public int DirtSnowy;
        public int Flowers;
        public int Glass;
        public int Grass;
        public int GrassF;
        public int GrassFDead;
        public int GrassFDry;
        public int GreystoneRubyOre;
        public int Ice;
        public int Lava;
        public int Leaves;
        public int LeavesOrange;
        public int LogBirch;
        public int LogOak;
        public int MushroomBrown;
        public int MushroomRed;
        public int MushroomTan;
        public int Oven;
        public int Planks;
        public int PlanksRed;
        public int Rock;
        public int RockMossy;
        public int Sand;
        public int SandGrey;
        public int SandRed;
        public int SandStoneRed;
        public int SandStoneRedElm;
        public int SandStoneRedSand;
        public int Stone;
        public int StoneCoalOre;
        public int StoneDiamondOre;
        public int StoneGoldOre;
        public int StoneGrassy;
        public int StoneGravel;
        public int StoneGrey;
        public int StoneGreySandy;
        public int StoneIronBrownOre;
        public int StoneIronGreenOre;
        public int StoneSandy;
        public int StoneSilverOre;
        public int StoneSnowy;
        public int StoneSnowy1;
        public int Water;
        public int WheatStage1;
        public int WheatStage2;
        public int WheatStage3;
        public int WheatStage4;
        public int Workbench;
    }
}